### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Oleander1212** [Harleythetech/IPHTV#1]
Dead links:
WWE network
Nickelodeon Jr.
One Sports +

Please add:
Uaap varsity channel

**Comment by Harleythetech** [comment]
Will update.

**Comment by Harleythetech** [comment]
![image](https://github.com/Harleythetech/IPHTV/assets/51787264/ac9e88d2-3cb7-4494-a1e7-3955bf1b8fa2)
![image](https://github.com/Harleythetech/IPHTV/assets/51787264/f915f7d1-2f65-472e-bc68-0133bdff5114)


WWE - Dead
One Sports+ - Alive
NICK JR - Alive


Please Provide link for UAPP Varsity CH

**Comment by Oleander1212** [comment]
Tinyurl.com link not working but if actual link is used, it's working. Used xplayer.

**Comment by Harleythetech** [comment]
i guess it varies from the player used, i grabed the links from various sources so idk much about it

**Comment by teenn009** [comment]
hello! great m3u playlist, but can you add more kids channel? such as disney xd, channel, jr and nickelodeon asia and boomerang? also hbo is not working, thank you!

**Comment by Pahndesal** [comment]
Deadlink:
GMA

**Comment by Harleythetech** [comment]
> Deadlink: GMA

Removed, will be looking into some links to revive it.

**Comment by Harleythetech** [comment]
> hello! great m3u playlist, but can you add more kids channel? such as disney xd, channel, jr and nickelodeon asia and boomerang? also hbo is not working, thank you!

Need to also look for active m3u8 links for this

**Comment by arbiepeligro** [comment]
Please Add

TV5
A2Z
Teleradyo Serbisyo
