### ISSUE TITLE
ACTIVE LINKS

### ISSUE THREAD

**Issue by arbiepeligro** [Harleythetech/IPHTV#3]
Please Add

TV5 HD
https://qp-pldt-live-grp-02-prod.akamaized.net/out/u/tv5_qp.m3u8

A2Z (via CIGNAL TV)
https://tv-noyzkie.serv00.net/streams/A2Z.m3u8

**Comment by Harleythetech** [comment]
gotchu, ill update back once added.

**Comment by Harleythetech** [comment]
now updated. thanks!

**Comment by Harleythetech** [comment]
added link :)
